name: Debug Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build debug apk
    runs-on: ubuntu-latest
    environment: DEBUG_BUILD
    steps:
      - name: Check out
        uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "corretto"
          cache: "gradle"
      - name: Build with Gradle
        env:
          EXAMPLE_APP_NAME: "${{ secrets.EXAMPLE_APP_NAME }}"
        run: ./gradlew assembleDebug
      - name: Upload apk file
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk